name: google_developer_student_clubs
description: A new Flutter project as a gift to GDSC.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.2
  rive: ^0.9.1
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2

  page_indicator: ^0.4.1
  flutter_hooks: ^0.18.5+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/

  fonts:
    - family: Mukta
      fonts:
        - asset: assets/Fonts/Mukta-Regular.ttf
        - asset: assets/Fonts/Mukta-SemiBold.ttf
          weight: 600
    - family: OpenSans
      fonts:
        - asset: assets/Fonts/OpenSans-Regular.ttf
        - asset: assets/Fonts/OpenSans-SemiBold.ttf
          weight: 600

    - family: Padauk
      fonts:
        - asset: assets/Fonts/Padauk-Regular.ttf
